apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 2048Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: foobar
    name: nfs-pvc
  nfs:
    path: /mnt/nfs_share 
    server: 192.168.0.2 
