apiVersion: v1
kind: Pod
metadata:
  name: network-tools 
  labels:
    name: network-tools-pod
spec:
  containers:
    - name: network-tools-pod
      image: gcr.io/sidecar-314513/network-tools:latest 
      volumeMounts:
        - name: nfsvol 
          mountPath: /mnt 
  securityContext:
      supplementalGroups: [100003] 
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc 
